name: Build TWRP
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build TWRP Recovery
        uses: lmpenguin/twrp-builder@main
        with:
          device: davinci
          manufacturer: xiaomi
          android_version: 9
