name: Build TWRP
on: push
jobs:
  build-twrp:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: sebastiansokol/twrp-builder@latest
        with:
          device: davinci
          codename: davinci
          vendor: xiaomi
          android: 9.0
